apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhfgdd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhfgdd
  template:
    metadata:
      labels:
        app: fhfgdd
    spec:
      containers:
      - image: okteto.dev/fhfgdd:latest
        name: fhfgdd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "0571b381-1db1-4c25-a2ed-4288ff7cce58"
        - name: Vless_Path
          value: "/vltyyjbdrgv"
        - name: Vmess_UUID
          value: "0571b381-1db1-4c25-a2ed-4288ff7cce58"
        - name: Vmess_Path
          value: "/vmfghmnbdrtg"
        - name: Share_Path
          value: "/v2link"
